language: julia
dist: focal

notifications:
  email: false

stages:
  - name: "Docs & Code Coverage"
  - name: Tests
    if: branch != master AND branch != develop AND NOT branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_script:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      bash .github/scripts/install-poppler-unix.sh
    fi

jobs:
  fast_finish: true
  allow_failures:
    julia: nightly
  include:
    - stage: "Docs & Code Coverage"
      name: "Codecov, Julia 1.5 (Linux, x64)"
      julia: 1.5
      os: linux
      arch: amd64
      script:
        - julia -e 'using Pkg; Pkg.build("PDFHighlights");
                    Pkg.add("Coverage"); using Coverage;
                    Pkg.test(coverage=true); Codecov.submit(process_folder())'
    - stage: "Docs & Code Coverage"
      name: "Documentation Build, Julia 1.5 (Linux, x64)"
      julia: 1.5
      os: linux
      arch: amd64
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(path=pwd());
                                    Pkg.build("PDFHighlights"), Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
    - stage: "Tests"
      name: "Julia 1.5 (macOS, x64)"
      julia: 1.5
      os: osx
      osx_image: xcode12
    - stage: "Tests"
      name: "Julia Nightly (Linux, x64)"
      julia: nightly
      os: linux
      arch: amd64
    - stage: "Tests"
      name: "Julia Nightly (macOS, x64)"
      julia: nightly
      os: osx
      osx_image: xcode12