name: BinaryBuilder

on:
  push:
    branches:
      - binaries

jobs:
  BinaryBuilder:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2
      - name: Install Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: 1.5
          arch: x64
      - name: Install BinaryBuilder
        run: julia -e 'using Pkg; Pkg.add("BinaryBuilder")'
      - name: Build Binaries
        run: julia --color=yes build_tarballs.jl --verbose --deploy=local
      - name: Test the package
        run: |
          cp -r test ~/.julia/dev/PDFHighlights_jll
          julia -e 'using Pkg; Pkg.develop(path="/home/runner/.julia/dev/PDFHighlights_jll")
                    Pkg.test("PDFHighlights_jll")'
      - name: Upload the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            products/*.tar.gz
            ~/.julia/dev/PDFHighlights_jll
