name: Docs & Code Coverage

on: push

defaults:
  run:
    working-directory: .github/scripts

jobs:
  coverage:
    name: Codecov, Julia 1.5 (Linux, x64)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.5
          arch: x64
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
  docs:
    name: "Documentation Build, Julia 1.5 (Linux, x64)"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.5
          arch: x64
      - uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}