name: TagBot
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.TAGBOT_PRIV }}
          user: Pavel Sobolev
          email: paveloom@mail.ru
          gpg: ${{ secrets.GPG_KEY }}
          gpg_password: ${{ secrets.GPG_PASSWORD }}
          branch: master