name: Tests

on:
  push:
    branches-ignore:
      - master
      - develop
    tags-ignore:
      - v*

defaults:
  run:
    working-directory: .github/scripts

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.5', 'nightly']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        julia-arch: [x86, x64]
        exclude:
          - os: ubuntu-latest
            julia-version: '1.5'
            julia-arch: x64
          - os: macOS-latest
            julia-arch: x86
    name: Julia
          ${{ ( matrix.julia-version == 'nightly' && 'Nightly' ) || matrix.julia-version }}
          (${{ ( matrix.os == 'ubuntu-latest' && 'Linux' ) || ( matrix.os == 'windows-latest' && 'Windows' ) || ( matrix.os == 'macOS-latest' && 'macOS' ) }},
          ${{ matrix.julia-arch }})
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/julia-runtest@latest